# Generated by Django 3.1.5 on 2021-02-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeti_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
