# Generated by Django 3.1.5 on 2021-01-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeti_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='video_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
