# Generated by Django 3.1.5 on 2021-02-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeti_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='year',
            new_name='object_id',
        ),
    ]
