# Generated by Django 3.1.5 on 2021-02-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeti_app', '0002_auto_20210205_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
