# Generated by Django 3.1.5 on 2021-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeti_app', '0002_auto_20210115_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
